Burritos1/Controllers/ApplicationUsersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Burritos1.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;

namespace Burritos1.Controllers
{
    [Authorize(Roles = "Administrador")]
    public class ApplicationUsersController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: ApplicationUsers
        public ActionResult Index()
        {
            return View(db.Users.ToList());
        }

        // GET: ApplicationUsers/Details/5
        [HttpGet]
        public ActionResult Details(string id)
        {

            List<SelectListItem> ListRoles = new List<SelectListItem>()
            {
              new SelectListItem {Text="Vendedor",Value="Vendedor", },
              new SelectListItem {Text="Administrador",Value="Administrador" }
            };
            ViewBag.ListRoles = ListRoles;

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ApplicationUser applicationUser = db.Users.Find(id);
            if (applicationUser == null)
            {
                return HttpNotFound();
            }
            return View(applicationUser);
        }
        
        [HttpPost]
        public ActionResult Details(SelectListItem ItemSeleccionado)
        {
            //var ItemSeleccionado.Text;
            string ListRoles = Request.Form["ListRoles"].ToString();
            if (User.Identity.IsAuthenticated)
            {
                using (ApplicationDbContext db = new ApplicationDbContext())
                {
                    var idUser = User.Identity.GetUserId();
                    var roleManager = new RoleManager<IdentityRole>(
                        new RoleStore<IdentityRole>(db));
                    //Creando el rol
                    //var resultado = roleManager.Create(new IdentityRole("Usuario"));
                    var userManager = new UserManager<ApplicationUser>(
                        new UserStore<ApplicationUser>(db));
                    //User esta en rol?
                    var userEstaenRol = userManager.IsInRole(idUser, ListRoles);
                    if(Request.Form["Add Role"] != null)
                    {
                        if (!userEstaenRol)
                        {
                            var resultado = userManager.AddToRole(idUser, ListRoles);
                            TempData["Message"] = "UsuarioNuevoRol";
                            db.SaveChanges();
                        }
                        else
                        {
                            TempData["Message"] = "UsuarioRolExistente";
                        }
                       // db.SaveChanges();
                    }
                    else
                    {
                        if (userEstaenRol)
                        {
                            if (Request.Form["Del Role"] != null)
                            {
                                //Remover Usuario de rol
                                var resultado = userManager.RemoveFromRole(idUser, ListRoles);
                                TempData["Message"] = "UsuarioRemovidoRol";
                                db.SaveChanges();
                            }      
                        }
                        else
                        {
                            //El usuario no estaba en el rol
                            TempData["Message"] = "UsuarioNoTeniaRol";
                        }
                        //db.SaveChanges();
                    }               
                    //GetRoles de Usuario 
                    //var roles = userManager.GetRoles(idUser);
                    //Remover Usuario de rol
                    //resultado = userManager.RemoveFromRole(idUser, "Usuario");
                    //borrar Rol
                    //var rolVendedor = roleManager.FindByName("Vendedor");
                    //roleManager.Delete(rolVendedor);
                }
            }
            return RedirectToAction("Index");
        }

        // GET: ApplicationUsers/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ApplicationUsers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Email,EmailConfirmed,PasswordHash,SecurityStamp,PhoneNumber,PhoneNumberConfirmed,TwoFactorEnabled,LockoutEndDateUtc,LockoutEnabled,AccessFailedCount,UserName")] ApplicationUser applicationUser)
        {
            if (ModelState.IsValid)
            {
                db.Users.Add(applicationUser);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(applicationUser);
        }

        // GET: ApplicationUsers/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ApplicationUser applicationUser = db.Users.Find(id);
            if (applicationUser == null)
            {
                return HttpNotFound();
            }
            return View(applicationUser);
        }

        // POST: ApplicationUsers/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Email,EmailConfirmed,PasswordHash,SecurityStamp,PhoneNumber,PhoneNumberConfirmed,TwoFactorEnabled,LockoutEndDateUtc,LockoutEnabled,AccessFailedCount,UserName")] ApplicationUser applicationUser)
        {
            if (ModelState.IsValid)
            {
                db.Entry(applicationUser).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(applicationUser);
        }

        // GET: ApplicationUsers/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ApplicationUser applicationUser = db.Users.Find(id);
            if (applicationUser == null)
            {
                return HttpNotFound();
            }
            return View(applicationUser);
        }

        // POST: ApplicationUsers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            ApplicationUser applicationUser = db.Users.Find(id);
            db.Users.Remove(applicationUser);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Burritos1/Controllers/UsuarioController.cs
using Burritos1.Models;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;

namespace Burritos1.Controllers
{
    public class UsuarioController : Controller
    {
        // GET: Usuario
        public ActionResult Index()
        {
            return RedirectToAction("BurritosenVenta");
        }

        public ActionResult BurritosenVenta()
        {
            BurritoContext db = new BurritoContext();
            var data = db.Database.SqlQuery<Producto>(
                @"SELECT * from dbo.Productoes Where Disponibles >0").ToList();
            return View(data);
        }
        [HttpGet]
        public ActionResult MostrarProducto(int id)
        {
            BurritoContext db = new BurritoContext();
            Producto producto = db.Productos.Find(id);
            if (producto != null)
            {
                //TempData["Message"] = "Exito";
                return View(producto);
            }
            return View();
        }
        [HttpPost]
        public ActionResult MostrarProducto(Producto mimodelo, string cantidad, string numero)
        {
            BurritoContext db = new BurritoContext();
            Producto producto = db.Productos.Find(mimodelo.Id);
            var data = db.Database.SqlQuery<Ordenes>(
                @"SELECT * from dbo.Ordenes WHERE idComprador = @idComprador", new SqlParameter("@idComprador", User.Identity.GetUserId())).ToList();
            Ordenes orden = new Ordenes();
            orden.Cantidad = int.Parse(cantidad);
            orden.idComprador = User.Identity.GetUserId();
            orden.Vendedor = producto.Vendedor;
            orden.idVendedor = producto.IdVendedor;
            orden.Producto = producto.Nombre;
            orden.Estado = "Nueva Orden";
            orden.Precio = producto.Costo;
            orden.idProducto = producto.Id;
            orden.FormadePago = "Efectivo";
            orden.TelCliente = numero;
            if (orden.Cantidad > producto.Disponibles)
            {
                TempData["Message"] = "Nohaytantos";
                return RedirectToAction("BurritosenVenta");
            }
            db.Ordenes.Add(orden);
            db.SaveChanges();
            TempData["Message"] = "BurritoOrden";
            return RedirectToAction("BurritosEnVenta");
        }
        public ActionResult MisOrdenes()
        {
            BurritoContext db = new BurritoContext();
            var data = db.Database.SqlQuery<Ordenes>(
                @"SELECT * FROM dbo.Ordenes 
                WHERE idComprador = @idComprador ", new SqlParameter("@idComprador", User.Identity.GetUserId())).ToList();
            if (data != null)
            { 
                return View(data);
            }
            return RedirectToAction("MostrarProducto");
        }
    }
}

Burritos1/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("BurritoApps", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Listar Usuarios", "Index", "ApplicationUsers")</li>
                    <li>@Html.ActionLink("Modo Vendedor", "Index", "Vendedor")</li>
                    <li>@Html.ActionLink("Modo Usuario", "Index", "Usuario")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Burritos1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - AplicacionesBurritow!</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("BurritoApps", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Inicio", "Index", "Home")</li>
                    <li>@Html.ActionLink("Acerca de", "About", "Home")</li>
                    <li>@Html.ActionLink("Contacto", "Contact", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - AplicacionesBurrito</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Burritos1/Views/Shared/_UserLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("BurritoApps", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Todos los Productos", "BurritosEnVenta", "Usuario")</li>
                    <li>@Html.ActionLink("Mis Ordenes","MisOrdenes","Usuario")</li>
                        @{
                            if (this.User.IsInRole("Vendedor"))
                            {
                                <li>@Html.ActionLink("Modo Vendedor", "Index", "Vendedor")</li>
                            }
                            if (this.User.IsInRole("Administrador"))
                            {
                                <li>@Html.ActionLink("Modo Administrador", "Index", "ApplicationUsers")</li>
                            }
                        }
                    
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - BurritoApps!</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Burritos1/Views/Shared/_VendorLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("BurritoApps", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Mis Burritos", "ListarProductos", "Vendedor")</li>
                    <li>@Html.ActionLink("Agregar Burritos", "AgregarProducto", "Vendedor")</li>
                    <li>@Html.ActionLink("Mis Ordenes", "MisOrdenes", "Vendedor")</li>
                    <li>@Html.ActionLink("Revisar Hielera", "RevisarHielera", "Vendedor")</li>
                    <li>@Html.ActionLink("Modo Usuario", "Index", "Usuario")</li>
                    @if (this.User.IsInRole("Administrador"))
                    {
                    <li>@Html.ActionLink("Modo Administrador", "Index", "ApplicationUsers")</li>
                    }
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>